### ISSUE TITLE
Hii bro , am working on an app using flutter local notification , am trying to add buttons to it but am getting errors when I click it , can U please help me to solve it ? 

### ISSUE THREAD

**Issue by ampro88** [AbrahamCoello/prueba_emqu_flutter#1]

**Comment by AbrahamCoello** [comment]
Hello, I'm late, but I can help you, I think the flutter_local_notifications package doesn't have support for that, however, you can help with another package for what you want, [here](https://www.fluttercampus.com/guide/273/add-action-button-on-local-notification-flutter/) is a sample one with examples
